add premium menu and new arrivals section and some minor style fixes
Saminsfw/healthy-restaurant pull request #2
Opened 2023-11-20 06:46 UTC by Saminsfw

2023-11-20 14:50 UTC, UmmarHamid commented
@Saminsfw I cannot find any screenshot attached, hence review is on hold!

2023-11-21 04:06 UTC, Saminsfw commented
![menu](https://github.com/Saminsfw/healthy-restaurant/assets/128600747/de4ec31e-537b-4ff1-bdea-ee60b21954e4)

2023-11-21 04:06 UTC, Saminsfw commented
![menu2](https://github.com/Saminsfw/healthy-restaurant/assets/128600747/1fe98677-8a74-470e-a586-2f1824cd24a0)

2023-11-21 04:19 UTC, UmmarHamid requested changes

2023-11-21 04:19 UTC, UmmarHamid commented on index.html
> +    <!-- Product Menu -->
Nice to have these section comments, it makes reading code easier!

2023-11-21 04:19 UTC, UmmarHamid commented on styles.css
> +  /* padding: 0 185px 0 147px; */
Lets remove this

2023-11-21 04:19 UTC, UmmarHamid commented on styles.css
> +  /* padding: 0 209px 0 159px; */
same

2023-11-21 04:19 UTC, UmmarHamid commented on styles.css
>    margin-bottom: 61px;
lets round this of to multiple of 4

2023-11-21 04:19 UTC, UmmarHamid commented on styles.css
>    padding: 17px 28px;
lets normalize

2023-11-21 06:29 UTC, UmmarHamid approved these changes

2023-11-21 06:29 UTC, merged